# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='totalups',
            field=models.IntegerField(default=0),
        ),
    ]
